# Generated by Django 4.2.1 on 2023-05-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0003_rename_temperature_weatherkiev_temperature_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherkiev',
            name='temperature_day',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='weatherkiev',
            name='temperature_night',
            field=models.IntegerField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='weatherkiev',
            name='weather_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
